info_en: "[event]"
info_cn: "[event信息]"
command: obdiag display scene run --scene=observer.event
task:
  - version: "[4.0.0.0, *]"
    steps:
      - type: sql
        sql: "SELECT
              /* MONITOR_AGENT */
              con_id tenant_id,
              CASE
              WHEN event_id = 10000 THEN 'INTERNAL'
              WHEN event_id = 13000 THEN 'SYNC_RPC'
              WHEN event_id = 14003 THEN 'ROW_LOCK_WAIT'
              WHEN (
                event_id >= 10001
                AND event_id <= 11006
              )
              OR (
                event_id >= 11008
                AND event_id <= 11011
              ) THEN 'IO'
              WHEN event LIKE 'latch:%' THEN 'LATCH'
              ELSE 'OTHER'
            END
              event_group,
              SUM(total_waits) AS total_waits,
              SUM(time_waited_micro / 1000000) AS time_waited
            FROM
              v$system_event
            WHERE
              v$system_event.wait_class <> 'IDLE'
              AND (
                con_id > 1000
                OR con_id = 1
              )
            GROUP BY
              tenant_id,
              event_group
            ORDER BY
              tenant_id,
              event_group;"
        global: true
