info: 'Check whether Error 4103 is reported when enable_sql_audit is set to True.'
task:
  - obversion: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where NAME="enable_sql_audit" and VALUE<>"True" ;'
      result:
        set_value: sql_audit
        # report_type: warning
        verify: "[ '0' ==  ${sql_audit} ]"
        err_msg: 'Unable to proceed because enable_sql_audit is set to False'
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_SQL_AUDIT where RET_CODE ="-4103";'
      result:
        set_value: err_4103
        verify_type: equal
        verify: 0
        err_msg: 'number of sql_error_4103 is #{err_4103}'



