info_en: "[memory problem]"
info_cn: "[内存问题]"
command: obdiag gather scene run --scene=observer.memory
task:
  - version: "[2.0.0.0, 4.0.0.0]"
    steps:
      - type: sql
        sql: "show variables like 'version_comment';"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.v$ob_cluster"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.__all_zone WHERE name='idc';"
        global: true
      - type: sql
        sql: "select svr_ip,zone,with_rootserver,status,block_migrate_in_time,start_service_time,stop_time,build_version from oceanbase.__all_server order by zone;"
        global: true
      - type: sql
        sql: "SELECT zone, concat(svr_ip, ':', svr_port) observer, cpu_capacity, cpu_total, cpu_assigned, cpu_assigned_percent, mem_capacity, mem_total, mem_assigned, mem_assigned_percent, unit_Num, round(`load`, 2) `load`, round(cpu_weight, 2) cpu_weight, round(memory_weight, 2) mem_weight, leader_count FROM oceanbase.__all_virtual_server_stat ORDER BY zone,svr_ip;"
        global: true
      - type: sql
        sql: "select tenant_id,tenant_name,primary_zone,compatibility_mode from oceanbase.__all_tenant;"
        global: true
      - type: sql
        sql: "show parameters like '%syslog_level%';"
        global: true
      - type: sql
        sql: "show parameters like '%syslog_io_bandwidth_limit%';"
        global: true
      - type: sql
        sql: "select count(*),tenant_id,zone_list,unit_count from oceanbase.__all_resource_pool group by tenant_id,zone_list,unit_count;"
        global: true
      - type: sql
        sql: "select * from oceanbase.__all_virtual_tenant_memstore_info where (active_memstore_used > major_freeze_trigger) or (total_memstore_used > memstore_limit);"
        global: true
      - type: sql # 查看内存占用最大的 20 个模块
        sql: "select `CONTEXT`, ROUND(USED / 1024 / 1024 / 1024, 2) as USED_GB from oceanbase.gv$memory group by `CONTEXT` ORDER BY USED DESC  limit 20;"
        global: true
      - type: sql # 查看内存状态
        sql: "select  /*+ READ_CONSISTENCY(WEAK), query_timeout (100000000) */ TENANT_ID, round(ACTIVE / 1024 / 1024 / 1024, 2) ACTIVE_GB, round(TOTAL / 1024 / 1024 / 1024, 2) TOTAL_GB, round(FREEZE_TRIGGER / 1024 / 1024 / 1024, 2) FREEZE_TRIGGER_GB, round(TOTAL / FREEZE_TRIGGER * 100, 2) percent_trigger, round(MEM_LIMIT / 1024 / 1024 / 1024, 2) MEM_LIMIT_GB from oceanbase.gv$memstore where tenant_id > 1000 or TENANT_ID = 1 order by tenant_id, TOTAL_GB desc;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.__all_virtual_trans_stat WHERE part_trans_action<=2 AND ctx_create_time < date_sub(now(), INTERVAL 600 SECOND) AND is_exiting != 1;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.__all_virtual_trans_stat WHERE part_trans_action > 2 AND ctx_create_time < date_sub(now(), INTERVAL 600 SECOND) AND is_exiting != 1;"
        global: true
      - type: sql
        sql: "SELECT table_id, partition_id, base_version, snapshot_version FROM oceanbase.__all_virtual_table_mgr WHERE table_type=0 except SELECT table_id, partition_idx, base_version, snapshot_version FROM oceanbase.__all_virtual_memstore_info limit 10;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.__all_virtual_tenant_memstore_allocator_info a,(select svr_ip,tenant_id from oceanbase.__all_virtual_tenant_memstore_info where (active_memstore_used > major_freeze_trigger)) b where a.svr_ip=b.svr_ip and a.tenant_id=b.tenant_id AND a.mt_is_frozen=1 ORDER BY mt_protection_clock limit 20;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.__all_virtual_tenant_memstore_allocator_info a,(select svr_ip,tenant_id from oceanbase.__all_virtual_tenant_memstore_info where (total_memstore_used > memstore_limit)) b where a.svr_ip=b.svr_ip and a.tenant_id=b.tenant_id AND a.mt_is_frozen=0 ORDER BY mt_protection_clock limit 20;"
        global: true
      - type: log
        grep: ""
        global: false
  - version: "[4.0.0.0, *]"
    steps:
      - type: sql
        sql: "show variables like 'version_comment';"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_ZONES;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_SERVERS;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.GV$OB_SERVERS;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_UNIT_CONFIGS;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_RESOURCE_POOLS;"
        global: true
      - type: sql
        sql: "SELECT * FROM oceanbase.DBA_OB_TENANTS;"
        global: true
      - type: sql
        sql: "SELECT c.TENANT_ID, e.TENANT_NAME, concat(c.NAME, ': ', d.NAME) `pool:conf`,concat(c.UNIT_COUNT, ' unit: ', d.min_cpu, 'C/', ROUND(d.MEMORY_SIZE/1024/1024/1024,0), 'G') unit_info FROM oceanbase.DBA_OB_RESOURCE_POOLS c, oceanbase.DBA_OB_UNIT_CONFIGS d, oceanbase.DBA_OB_TENANTS e WHERE c.UNIT_CONFIG_ID=d.UNIT_CONFIG_ID AND c.TENANT_ID=e.TENANT_ID AND c.TENANT_ID>1000 ORDER BY c.TENANT_ID;"
        global: true
      - type: sql
        sql: "SELECT a.TENANT_NAME,a.TENANT_ID,b.SVR_IP FROM oceanbase.DBA_OB_TENANTS a, oceanbase.GV$OB_UNITS b WHERE a.TENANT_ID=b.TENANT_ID;"
        global: true
      - type: sql
        sql: "show parameters like '%syslog_level%';"
        global: true
      - type: sql
        sql: "show parameters like '%syslog_io_bandwidth_limit%';"
        global: true
      - type: sql
        sql: "select * from oceanbase.GV$OB_MEMSTORE limit 20"
        global: true
      - type: ssh # 可看到租户的规格、线程、队列及请求统计等信息，且这条日志每个租户每 30s 打印一次
        ssh: "grep 'dump tenant info.tenant=' ${observer_data_dir}/log/observer.log | sed 's/,/,/g'"
        global: false
      - type: log
        grep: ""
        global: false
