info: 'Check whether any module is using more than 10GB of memory.'
task:
  - obversion: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: '
  SELECT  hold/1024/1024/1024 AS hold_g, used/1024/1024/1024 AS used_g  
  FROM oceanbase.__all_virtual_memory_info  
  order by hold desc limit 1;'
      result:
        set_value: mod_max_memory
        report_type: warning
        verify_type: max
        verify: 10
        err_msg: 'mod_max_memory over 10G'