OBDIAG:
  BASIC:
    config_backup_dir: /tmp/oceanbase-diagnostic-tool/conf
    file_number_limit: 20
    file_size_limit: 2G
  LOGGER:
    log_dir: /tmp/oceanbase-diagnostic-tool/log
    log_filename: obdiag.log
    file_handler_log_level: DEBUG
    log_level: INFO
    mode: obdiag
    stdout_handler_log_level: DEBUG
OCP:
  LOGIN:
    url: http://xxx.xxx.xxx.xxx:xxxx
    user: xxx
    password: xxx
  METADB:
    ip: xxx.xxx.xxx.xxx
    port: xxx
    user: xxx
    password: xxx
    dbname: xxx
OBCLUSTER:
  cluster_name: xxx
  host: xxx.xxx.xxx.xxx
  port: xxx
  user: xxx
  password: xxx
NODES:
- ip: xxx.xxx.xxx.xxx
  port: xxx
  user: xxx
  password: xxx
  private_key: xxx
  home_path: xxx
CHECK:
  ignore_obversion: false
  report:
    report_path: "./check_report/"
    export_type: table
  package_file: "~/.obdiag/check_package.yaml"
  tasks_base_path: "~/.obdiag/tasks/"
