obdiag:
  basic:
    config_path: ~/.obdiag/config.yml
    config_backup_dir: ~/.obdiag/backup_conf
    file_number_limit: 20
    file_size_limit: 2G
    dis_rsa_algorithms: 0
  logger:
    log_dir: ~/.obdiag/log
    log_filename: obdiag.log
    file_handler_log_level: DEBUG
    log_level: INFO
    mode: obdiag
    stdout_handler_log_level: INFO
check:
  ignore_version: false
  work_path: "~/.obdiag/check"
  report:
    report_path: "./check_report/"
    export_type: table
  tasks_base_path: "~/.obdiag/check/tasks/"
gather:
  scenes_base_path: "~/.obdiag/gather/tasks"
rca:
  result_path: "./rca/"
