obdiag:
  basic:
    config_path: ~/.obdiag/config.yml
    config_backup_dir: ~/.obdiag/backup_conf
    file_number_limit: 50
    file_size_limit: 5G
    dis_rsa_algorithms: 0
    strict_host_key_checking: 0
  logger:
    log_dir: ~/.obdiag/log
    log_filename: obdiag.log
    file_handler_log_level: DEBUG
    log_level: INFO
    mode: obdiag
    stdout_handler_log_level: INFO
    error_stream: sys.stdout
    silent: false
  ssh_client:
    remote_client_sudo: 0
    cmd_exec_timeout: 180
analyze:
  thread_nums: 3
check:
  ignore_version: false
  work_path: "~/.obdiag/check"
  max_workers: 12
  report:
    report_path: "./check_report/"
    export_type: table
  tasks_base_path: "~/.obdiag/check/tasks/"
gather:
  scenes_base_path: "~/.obdiag/gather/tasks"
  redact_processing_num: 3
  thread_nums: 3
  gather_log:
    search_version: 2
rca:
  result_path: "./obdiag_rca/"
