info: 'To detect dependent software, refer to: https://www.oceanbase.com/docs/enterprise-oceanbase-ocp-cn-1000000000125643'
task:
  - steps:
    - type: ssh
      ssh: 'if command -v swapon &>/dev/null; then     echo "exist"; fi'
      result:
        set_value: swapon_exist
        report_type: execution
        verify: '[ "exist" != "${swapon_exist}" ]'
        err_msg: 'Do not warning. swapon is exist. We will check the swap'
    - type: ssh
      ssh: 'swapon --summary | grep -q "^" && echo "used" || echo "not used"'
      result:
        set_value: swapon_switch
        report_type: warning
        verify: '[ "not used" == "${swapon_switch}" ]'
        err_msg: 'swapon need be closed. Now , it is #{swapon_switch}.'