info: 'check SELinux by getenforce. refer to: https://www.oceanbase.com/docs/enterprise-oceanbase-ocp-cn-1000000000125643'
task:
  - steps:
    - type: ssh
      ssh: 'if command -v getenforce &>/dev/null; then     echo "exist"; fi'
      result:
        set_value: getenforce_exist
        report_type: execution
        verify: '[ "exist" != "${getenforce_exist}" ]'
        err_msg: 'Do not warning. getenforce is exist. We will check SELinux by getenforce'
    - type: ssh
      ssh: "getenforce"
      result:
        set_value: SELinux_switch
        report_type: warning
        verify: "[ 'Disabled' == ${SELinux_switch} ]"
        err_msg: 'SELinux need Disabled. Now , it is #{SELinux_switch}.'