
info: |
  'To detect kernel parameters, refer to: https://www.oceanbase.com/docs/enterprise-oceanbase-ocp-cn-1000000000125643'
task:
  - steps:
    - type: get_system_parameter
      parameter: net.ipv4.ip_local_port_range
      result:
        set_value: ip_local_port_range
        verify: '[[ -n "$ip_local_port_range" && "$ip_local_port_range" != "-1" ]]'
        err_msg: "ip_local_port_range is #{ip_local_port_range} . Please check net.ipv4.ip_local_port_range on your node"
    - type: ssh
      ssh: "echo \"#{ip_local_port_range}\" | awk '{print $1}'"
      result:
        set_value: ip_local_port_range_min
        report_type: warning
        verify_type: equal
        verify: 3500
        err_msg: 'ip_local_port_range_min : #{ip_local_port_range_min} is a non recommended value, recommended value is 3500'
    - type: ssh
      ssh: "echo \"#{ip_local_port_range}\" | awk '{print $2}'"
      result:
        set_value: ip_local_port_range_max
        report_type: warning
        verify_type: equal
        verify: 65535
        err_msg: 'ip_local_port_range_max : #{ip_local_port_range_max} is a non recommended value, recommended value is 65535'