
info: |
  'To detect kernel parameters, refer to: https://www.oceanbase.com/docs/enterprise-oceanbase-ocp-cn-1000000000125643'
task:
  - steps:
    - type: get_system_parameter
      parameter: net.ipv4.tcp_wmem
      result:
        set_value: tcp_wmem
    - type: ssh
      ssh: "echo \"#{tcp_wmem}\" | awk '{print $1}'"
      result:
        set_value: tcp_wmem_min
        report_type: warning
        verify_type: between
        verify: "[4096,8192]"
        err_msg: 'net.ipv4.tcp_wmem_min : #{tcp_wmem_min} is a non recommended value, recommended value is 4096 ≤ min ≤ 8192'
    - type: ssh
      ssh: "echo \"#{tcp_wmem}\" | awk '{print $2}'"
      result:
        set_value: tcp_wmem_default
        report_type: warning
        verify_type: between
        verify: "[65536,131072]"
        err_msg: 'net.ipv4.tcp_wmem_default : #{tcp_wmem_default} is a non recommended value, recommended value :is 65536 ≤ default≤ 131072'
    - type: ssh
      ssh: "echo \"#{tcp_wmem}\" | awk '{print $3}'"
      result:
        set_value: tcp_wmem_max
        report_type: warning
        verify_type: between
        verify: "[8388608,16777216]"
        err_msg: 'net.ipv4.tcp_wmem_max : #{tcp_wmem_max} is a non recommended value, recommended value is 65536 ≤ max≤ 131072'
