info: 'Check when running sysbench  , cluster paramters'
task:
  - obversion: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where Name="enable_record_trace_log" and VALUE <> "False";'
      result:
        set_value: enable_record_trace_log
        verify_type: equal
        verify: 0
        err_msg: "cluster's enable_record_trace_log is true , need to change False"
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where Name="enable_perf_event" and VALUE <> "False";'
      result:
        set_value: enable_perf_event
        verify_type: equal
        verify: 0
        err_msg: "cluster's enable_perf_event is true , need to change False"
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where Name="enable_sql_audit" and VALUE <> "False";'
      result:
        set_value: enable_sql_audit
        verify_type: equal
        verify: 0
        err_msg: "cluster's enable_sql_audit is true , need to change False"



