info: 'Check when running sysbench, cluster paramters'
task:
  - obversion: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: "SELECT GROUP_CONCAT(TENANT_NAME) AS tenant_names
FROM oceanbase.DBA_OB_TENANTS
WHERE TENANT_TYPE='USER' and PRIMARY_ZONE LIKE '%;%';"
      result:
        set_value: not_RANDOM
        verify: '[ -z "$not_RANDOM" ]'
        err_msg: "The PRIMARY_ZONE of the existing tenant is not RANDOM : #{not_RANDOM}"

