info: 'Check when sysbench free , cluster info about memory_limit'
task:
  - obversion: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select VALUE from oceanbase.GV$OB_PARAMETERS where Name="cpu_count";'
      result:
        set_value: cpu_count
        verify_type: equal
        report_type: execution
        verify: 0
        err_msg: 'cpu_count is #{cpu_count} , need to calculate the relationship between cpu_count and the number of system CPUs'
    - type: ssh
      ssh: "lscpu | grep '^CPU(s):' | awk '{print $2}'"
      result:
        set_value: os_cpu_count
    - type: ssh
      ssh: 'echo "#{cpu_count}*100/#{os_cpu_count}" | bc'
      result:
        set_value: result
        verify_type: between
        verify: "[90,100]"
        err_msg: 'cpu_count/os_cpu_count is #{result}%,is not between 80 and 100'
        
        
    

