info: 'Check whether data_dir and log_dir_disk are on the same disk.'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: ssh
      ssh: 'find #{remote_data_dir} -name "sstable"'
      result:
        set_value: data_dir_path
        verify: '[ -n "${data_dir_path}" ]'
        err_msg: "data_dir_path is null . Please check your nodes.data_dir need absolute Path"
    - type: ssh
      ssh: "df -h #{data_dir_path} | grep '/' | awk '{print $6}'"
      result:
        set_value: data_dir_disk
    - type: ssh
      ssh: 'find #{remote_redo_dir} -name "clog"'
      result:
        set_value: log_dir_path
        verify: '[ -n "${log_dir_path}" ]'
        err_msg: "log_dir_path is null . Please check your nodes.redo_dir need absolute Path"
    - type: ssh
      ssh: "df -h #{log_dir_path} | grep '/' | awk '{print $6}'"
      result:
        set_value: log_dir_disk
        verify: '[ "${data_dir_disk}" != "${log_dir_disk}" ]'
        err_msg: "ip:#{remote_ip} ,data_dir and log_dir_disk are on the same disk."
    - type: ssh
      ssh: "df -T  #{data_dir_path} | grep \"/\"|awk '{if ($3 > 17179869184 && $2 != \"xfs\") print \"1\"; else print \"0\"}'"
      result:
        set_value:  file_system
        verify_type: equal
        verify: 0
        err_msg: "the data_dir_path of disk size over 16TB ,the type must be xfs"

    - type: ssh
      ssh: "df -Th  #{log_dir_path} | grep '/' | awk '{print $2}'"
      result:
        set_value:  file_system
        verify: '[ "${file_system}" == "xfs" ] || [ "${file_system}" == "ext4" ] || [ "${file_system}" == "xfs" ]'
        err_msg: "ip:#{remote_ip} ,log_dir_path: #{log_dir_path} file_system is not xfs or ext4."
    - type: ssh
      ssh: "df -T  #{log_dir_path} | grep \"/\"|awk '{if ($3 > 17179869184 && $2 != \"xfs\") print \"1\"; else print \"0\"}'"
      result:
        set_value:  file_system
        verify_type: equal
        verify: 0
        err_msg: "the log_dir_path of disk size over 16TB ,the type must be xfs"

    - type: ssh
      ssh: "df -Th  #{data_dir_path} | grep '/' | awk '{print $2}'"
      result:
        set_value:  file_system
        verify: '[ "${file_system}" == "xfs" ] || [ "${file_system}" == "ext4" ]'
        err_msg: "ip:#{remote_ip} ,data_dir_path: #{data_dir_path} file_system is not xfs or ext4."
    - type: ssh
      ssh: "df -Th  #{remote_home_path} | grep '/' | awk '{print $2}'"
      result:
        set_value:  file_system
        verify: '[ "${file_system}" == "xfs" ] || [ "${file_system}" == "ext4" ]'
        err_msg: "ip:#{remote_ip} ,home_path: #{remote_home_path} file_system is not xfs or ext4."

