info: "There are too many table histories for a tenant in the cluster, and when the machine restarts, the schema refresh will continue to report -4013, resulting in the inability to refresh the corresponding tenant's schema for a particular machine."
task:
  - version: "[4.1.0.0,4.1.0.1]"
    steps:
    - type: sql
      sql: 'select name from oceanbase.__all_virtual_tenant_parameter_stat where name like "%ob_enable_plan_cache%" and value like "%true%";'
      result:
        set_value: ob_enable_plan_cache
        verify: '[ -z "ob_enable_plan_cache" ]'
        err_msg: 'On this version, ob_enable_plan_cache suggestion to close'

