info: 'A table found two records in information_schema.tables. KBA-50000056'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.__all_virtual_table_stat where table_id = partition_id and (tenant_id,table_id) in (select tenant_id, table_id from oceanbase.__all_virtual_table where part_level != 0);'
      result:
        set_value: err_table_count
        # report_type: warning
        verify_type: equal
        verify: 0
        err_msg: 'Find have table found two records in information_schema.tables. the number of err_table_count is : #{err_table_count}.  Please get more info by "select * from oceanbase.__all_virtual_table_stat where table_id = partition_id and (tenant_id,table_id) in (select tenant_id, table_id from oceanbase.__all_virtual_table where part_level != 0);". And you can by "delete from __all_table_stat where table_id=partition_id and table_id=${partition table table_id};" and "delete from __all_column_stat where table_id=partition_id and table_id=${partition table table_id};" to fix it.'
